### ISSUE TITLE
name correction suggestion for [Emiliana  huxleyi], [Lagenisma coscinodiscii], and [Pirsonia eucampia]

### ISSUE THREAD

**Issue by kbseah** [globalbioticinteractions/globi-taxon-names#17]
Hi!
I found a few misspelled taxon names on a [globi page](https://www.globalbioticinteractions.org/?accordingTo=globi%3Adebpaul%2FDIDB&interactionType=ecologicallyRelatedTo&sourceTaxon=no%3Amatch). After reviewing the data sources and relevant taxonomic tools like the [globalnames resolver](https://resolver.globalnames.org), I think that suggestion below might be helpful.

If you'd prefer me to open single issues for each in the future, please let me know.

 Thanks!

| name | suggested name | name url reference | notes
| --- | --- | --- | ---
| Emiliana  huxleyi | Emiliania huxleyi | https://www.marinespecies.org/aphia.php?p=taxdetails&id=115104 | common misspelling
| Lagenisma coscinodiscii | Lagenisma coscinodisci | https://www.marinespecies.org/aphia.php?p=taxdetails&id=345480 | 
| Pirsonia eucampia | Pirsonia eucampiae | https://www.marinespecies.org/aphia.php?p=taxdetails&id=118064 |

**Comment by kbseah** [comment]
thank you, @jhpoelen !

**Comment by jhpoelen** [comment]
@kbseah thanks for sharing your notes on the taxonomic name spelling. I've created individual issues to let the provider of the data ( @FloraVincent ) know about your notes. Also, I've included your suggestions in GloBI's list of name adjustments. 

https://github.com/globalbioticinteractions/globi-taxon-names/commit/678a48776080e32ad78412c7bc7bfd8ff5b045aa

https://github.com/FloraVincent/DIDB/issues/4

https://github.com/FloraVincent/DIDB/issues/5

https://github.com/FloraVincent/DIDB/issues/6

Thanks again, and please be patient as your suggestions are integrated.

**Comment by jhpoelen** [comment]
If you feel this issue was addressed appropriately, please close this issue. If not, please let me know how you'd like to proceed.
