### ISSUE TITLE
"Bat" incorrectly mapped to "Bat SARS-like coronavirus"

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globi-taxon-names#6]
When searching for "Severe acute respiratory syndrome-related coronavirus" or by NCBI taxon https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=694009 , GloBI https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=NCBI%3A694009 produced a interaction of the virus having a parasite (see attached sceenshot). 

![Screenshot from 2020-11-30 11-13-45](https://user-images.githubusercontent.com/1084872/100653833-d1a07280-32fd-11eb-8e5b-09452fff8b4c.png)

This is likely due to overly eager taxonomic name matching ("Bat" matched with "Bat SARS-like coronavirus") in combination with common name usage (e.g., "Bat" instead of a scientific name).

**Comment by jhpoelen** [comment]
Note that https://resolver.globalnames.org resolves "Bat" to various corona viruses. 

See attached screenshot. 

![Screenshot from 2020-11-30 11-21-27](https://user-images.githubusercontent.com/1084872/100654193-4f647e00-32fe-11eb-99b1-a02342a56dd5.png)

**Comment by jhpoelen** [comment]
@katjaschulz - any chance we can add a refutation rule to the EOL integration that labels all interactions in which a virus is anything other than a pathogen or hosted object?

**Comment by KatjaSchulz** [comment]
We already have the following virus-specific refutation rule: "Records of other organisms parasitizing or eating viruses are likely to be errors."

Which filters out records where:
sourceTaxon does NOT have kingdom "Viruses"
AND targetTaxon has kingdom "Viruses"
AND associationType is: 
"ectoparasite of" (http://purl.obolibrary.org/obo/RO_0002632) OR 
"endoparasite of" (http://purl.obolibrary.org/obo/RO_0002634) OR 
"parasite of" (http://purl.obolibrary.org/obo/RO_0002444) OR 
"kleptoparasite of" (http://purl.obolibrary.org/obo/RO_0008503) OR 
"parasitoid of" (http://purl.obolibrary.org/obo/RO_0002208) OR 
"pathogen of" (http://purl.obolibrary.org/obo/RO_0002556) OR 
"eats" (http://purl.obolibrary.org/obo/RO_0002470) OR 
"preys on" (http://purl.obolibrary.org/obo/RO_0002439)

We could expand the refutation rule above to include records where viruses are the sourceTaxon.  It would probably make sense to filter out records where:
sourceTaxon has kingdom "Viruses"
AND targetTaxon does NOT have kingdom "Viruses"
AND associationType is: 
"has ectoparasite" (http://purl.obolibrary.org/obo/RO_0002633) OR 
"has endoparasite" (http://purl.obolibrary.org/obo/RO_0002635) OR 
"parasitized by" (http://purl.obolibrary.org/obo/RO_0002445) OR 
"kleptoparasitized by" (http://purl.obolibrary.org/obo/RO_0008504) OR 
"has parasitoid" (http://purl.obolibrary.org/obo/RO_0002209)  OR 
"has pathogen" (http://purl.obolibrary.org/obo/RO_0002557) OR 

Some bacteria & protists eat viruses, so rules we can't have simple virus/non-virus rules for "is eaten by" (http://purl.obolibrary.org/obo/RO_0002471) OR "is preyed upon by" (http://purl.obolibrary.org/obo/RO_0002458)

We currently recode (but don't refute) records where the sourceTaxon has kingdom "Viruses" and associationType is "eats" (http://purl.obolibrary.org/obo/RO_0002470). Here we simply change the associationType to "pathogen of" (http://purl.obolibrary.org/obo/RO_0002556).

**Comment by jhpoelen** [comment]
@KatjaSchulz neat to see that you already have extensive rules for cases where viruses are targets. 

Extending this to include viruses as source taxa makes total sense to me. This extension would likely flag the suspicious (some virus) -[:has parasite]->(some organism) interaction recorded in this issue. 

Is there anything I can help with to verify that the new to-be-added rule is working ok?

**Comment by KatjaSchulz** [comment]
I'll let you know when it's implemented, so you can check to see if it has the desired effect.

**Comment by KatjaSchulz** [comment]
@jhpoelen Eli implemented the new refutation filters and updated the refuted records resource: https://opendata.eol.org/dataset/globi/resource/92595520-35f3-48f2-95cf-ea67f7c455c3
However, there were no records that met the "virus has non-virus parasite etc." criteria in the current GloBI resource, so for now we don't have any refuted records from this filter.

**Comment by jhpoelen** [comment]
hey @KatjaSchulz - Thanks for the update on the refuted interaction data update you created.

I find it odd that you didn't find any suspicious virus interactions, as I can find a record claiming that a virus is being parasitized by a plant (see screenshot of https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=NCBI%3A694009). 

![Screenshot from 2020-12-16 14-12-55](https://user-images.githubusercontent.com/1084872/102412847-e3923e80-3fa8-11eb-9e9a-79c56106c165.png)

As I was digging into the provenance of all this data, I find that the page https://opendata.eol.org/dataset/globi/resource/92595520-35f3-48f2-95cf-ea67f7c455c3 , that contains the related refutation resource, was last updated 2020-05-27 - is that date stamp correct? 

![Screenshot from 2020-12-16 14-10-41](https://user-images.githubusercontent.com/1084872/102412971-189e9100-3fa9-11eb-8df9-047f39653f12.png)

**Comment by KatjaSchulz** [comment]
Ah, I see what the problem is here: Bat SARS-like coronavirus is not recognized as a virus because the "kingdom" value we get for this taxon is "Orthornavirae" rather than "Viruses."  Bat SARS-like coronavirus is mapped to NCBI which treats "Viruses" as a superkingdom and then has a bunch of viral kingdoms. I'll ask Eli to fix this by adding all the NCBI viral kingdoms to the filter.  Hopefully, that will take care of most of these cases.

**Comment by jhpoelen** [comment]
Thanks for checking - looking forward to your update!

**Comment by KatjaSchulz** [comment]
@jhpoelen Eli has updated the refuted records resource. It now catches relevant associations mapped to the NCBI viral kingdoms:
https://opendata.eol.org/dataset/globi/resource/92595520-35f3-48f2-95cf-ea67f7c455c3

**Comment by jhpoelen** [comment]
@KatjaSchulz Wow! That was quick! 

Keeping issue open until the changes propagate. Thanks the update and for being patient as I am reviewing the refuted names.

**Comment by jhpoelen** [comment]
@KatjaSchulz your refutation records are coming through loud and clear. For instance, see attached screenshot from https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=NCBI%3A694009 in which a common name "Civet" was linked to https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=231513 (Civet SARS CoV SZ3/2003) via https://resolver.globalnames.org . 

![Screenshot from 2020-12-28 13-19-56](https://user-images.githubusercontent.com/1084872/103243694-7c14b100-490f-11eb-8a7c-6e29829b6f2c.png)

With your refutation dataset, errors like those introduced by name linking services can be more easily tracked.

In this case, I'll have to figure out a way to exclude the "greedy" matches provided by a third party service. Please stay tuned . . . and thanks for being patient.

**Comment by KatjaSchulz** [comment]
Very cool!  Thanks for letting me know. We're probably still missing a few, but it's definitely progress.

**Comment by jhpoelen** [comment]
After introducing methods to prevent invalid name mappings like "Bat" -> "Bat SARS-like coronavirus" from propagating from globalnames resolver into the GloBI, and after removing invalid mappings in GloBI Taxon Name Graph v0.3.28 [1], previously suspicious interactions like "Bat SARS-like coronavirus parasite of X" are no longer reported.  

Now, query https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=NCBI%3A694009 (see attached screenshot) produces only the refutation record provided by @KatjaSchulz et al. , indicating the refuted claim is no longer made. 

![Screenshot from 2021-01-20 16-10-52](https://user-images.githubusercontent.com/1084872/105256601-e4d00180-5b3a-11eb-9c25-da1547eebe9e.png)



[1] Poelen, Jorrit H. (2021). Global Biotic Interactions: Taxon Graph (Version 0.3.28) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.4451472
